steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$juju-460619/myDeploy1', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$juju-460619/myDeploy1']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'myDeploy1', '--image', 'gcr.io/$juju-460619/myDeploy1', '--region', 'europe-west1', '--platform', 'managed', '--allow-unauthenticated']
images:
- 'gcr.io/$juju-460619/myDeploy1'