steps:
  # Étape 1 : Build de l'image Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/mydeploy1:latest', '.']
  
  # Étape 2 : Push vers Google Container Registry (GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/mydeploy1:latest']
  
  # Étape 3 : Déploiement sur Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'mydeploy1',
      '--image', 'gcr.io/$PROJECT_ID/mydeploy1:latest',
      '--region', 'europe-west1',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]
