steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$projetrevision-461620/mydeploy1', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$projetrevision-461620/mydeploy1']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'mydeploy1', '--image', 'gcr.io/$projetrevision-461620/mydeploy1', '--region', 'europe-west1', '--platform', 'managed', '--allow-unauthenticated']
images:
- 'gcr.io/$projetrevision-461620/mydeploy1'